# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CountDownTimerForTableView' do

pod 'MJRefresh', '~> 3.1.0'

end

target 'CountDownTimerForTableViewTests' do

end

